apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
type: Opaque
stringData:
  DATABASE_URL: "postgresql://oficina:<senha>@<endpoint-do-rds>:5432/oficina_db?schema=public"
  JWT_SECRET: "<segredo-com-minimo-32-caracteres>"
  JWT_CLIENTE_SECRET: "<outro-segredo-com-minimo-32-caracteres>"
  NEW_RELIC_LICENSE_KEY: "<chave-de-ingestao-do-new-relic>"
  SMTP_HOST: "<smtp.exemplo.com>"
  SMTP_USER: "<usuario-smtp>"
  SMTP_PASS: "<senha-smtp>"
